server/app.js
=> [Modify] Modify app.js

server/app.js
=> [Fix] Fix app.js

server/models/project.js, server/models/todo.js, server/models/user.js
Edit p_id to pid, add foreignkey
Edit td_id to tdid, add foreignkey
Edit u_id to uid, add auth
=> [Edit] Edit project.js , todo.js, user.js

server/app.js, server/models/assign_r.js, server/models/list.js
Fix models.sequelize.sync in app.js
Fix u_id, td_id to uid, tdid in list.js
Fix u_id, p_id to uid, pid in assign_r.js
=> [Fix] Fix app.js, assign_r.js, list.js

src/app/index.css, src/app/layout/footer.html, src/app/layout/layout.controller.js, src/app/layout/login.html, src/app/main/main.controller.js, src/app/main/main.css, src/app/main/main.html
Edit main.html and main.controller.js
=> [Edit] Edit Main Page

server/models/user.js, server/routes/admin.js, server/routes/index.js
Add routing PUT '/admin/user/{uid}' to admin.js and POST '/user' to index.js and edit user.js
=> [Edit] Edit admin.js and index.js and user.js

src/app/index.css, src/app/layout/layout.controller.js
Show sidebar on right when enlarging the main page. Add shadow on
sidebar.
=> [Add] Sidebar Shadow

src/app/admin/admin.project.controller.js, src/app/admin/admin.project.html, src/app/admin/admin.project.modify.html, src/app/admin/admin.project.view.html, src/app/admin/admin.project.write.html, src/app/admin/admin.users.controller.js, src/app/admin/admin.users.html, src/app/index.css, src/app/index.route.js, src/app/layout/sidebar/admin.sidebar.html
Add admin.project.html, #.view.html, #.write.html, #.modify.html, and #.controller.js to make admin-project-manager page.
Add admin.users.html and #.controller.js to make admin-user-manager page.
Edit index.css to decorate admin-project-manager page.
Edit index.route.js to route admin-project-manager page and admin-user-manager page.
=> Add Admin-Project-Manager Page and Admin-User-Manager Page

server/app.js, server/routes/user.js
=> [Add] Add routing to user.js

server/routes/admin.js, server/routes/index.js, server/routes/user.js
Add routing POST '/login' and GET '/session' to index.js
and add try and catch to GET '/project' in admin.js
and move POST '/' from index.js to user.js
=> [Edit] Admin.js and index.js and user.js

server/routes/user.js
Add routing PUT '/user' and GET '/:uid' to user.js
=> [Edit] edit user.js

server/app.js, server/routes/project.js
Add routing GET '/project/:uid' to project.js
Add routing '/project' to app.js
=> [Add] Create new file project.js

server/config/config.json, src/app/admin/admin.project.html, src/app/layout/layout.controller.js, src/app/layout/sidebar/sidebar.html
Add link on sidebar menu such as project admin and user admin.
=> [Add] Add Link On Sidebar Menu

server/routes/index.js
add routing GET '/logout' to index.js
=> [Edit] Edit index.js

src/app/admin/admin.project.write.html, src/app/admin/admin.users.controller.js
Enabled the admin to made it possible to fix and erase users and their information in the dummy db.
=> [Edit] Edit 2 files : admin.users.html and admin.project.write.html

server/routes/project.js
Add routing POST '/:uid/:pid' to project.js
Add routing DELETE '/:uid/:pid' to project.js
=> [Edit] Edit project.js

src/app/index.css, src/app/index.route.js, src/app/layout/loginRegister.html
1. Add loginRegister__form class to change to layout of loginRegister page
2. Apply new css to loginRegister page
=> [Edit] Index.css / loginRegister.html

server/routes/admin.js, server/routes/project.js
Remove try and catch statement and add admin author to routing GET '/project' and POST '/project' and PUT '/user/:uid'
=> [Edit] Edit routing to admin.js

server/routes/admin.js
Add routing GET '/users' and PUT '/users' in admin.js file
=> [Edit] Add routing to admin.js

server/routes/admin.js, server/routes/project.js
Fix error in project.js and add attribute to routing GET '/users' in
admin.js
=> [Fix] Fix admin.js and project.js

server/routes/admin.js, server/routes/index.js
=> pull request

server/routes/admin.js, src/app/layout/login.controller.js, src/app/layout/login.html
Edit html and controller to login and get session.
=> [Edit] login.html and login.controller.js

src/app/index.constants.js, src/app/layout/login.controller.js, src/app/layout/login.html
Edit index.constants.js to define SHA256, login controller to apply SHA256, and login.html to make input have appropriate ng-model.
=> [Edit] Apply SHA256 to password

server/routes/project.js, server/routes/user.js
Add routing POST '/project/todo' in project.js
=> [Edit] Add routing to project.js file

src/app/PM/project/pm.project.controller.js, src/app/PM/project/pm.project.html, src/app/PM/project/pm.project.modify.html, src/app/PM/project/pm.project.view.html, src/app/PM/project/pm.project.write.html, src/app/admin/pm.project.modify.html, src/app/index.constants.js, src/app/index.route.js, src/app/layout/sidebar.html
Add PM page view, PM controller and PM folder.
=> [Add] Add PM Page

server/routes/admin.js, server/routes/project.js
Add routing GET '/user/:uid/:pid' to admin.js
Add routing GET '/:uid/:pid' to project.js
=> [Edit] Add routing to project.js and admin.js

src/app/main/main.html
Disabled modify, delete button of user.
=> [Edit] Main.html

src/app/admin/account/admin.users.html, src/app/admin/account/admin.users.modify.html, src/app/admin/account/admin.users.todo.controller.js, src/app/admin/account/admin.users.todo.html, src/app/index.route.js
Add todo view page for admin user and edit user modify page to send
project information to todo page.
=> [Add] Todo page in admin page

src/app/layout/layout.controller.js, src/app/layout/sidebar/admin.sidebar.html, src/app/layout/sidebar/sidebar.html, src/app/main/main.html
Disable some buttons on the sidebar
Add link on Home button on the sidebar (to the main page)
=> [Edit] Layout.controller.js / admin.sidebar.html and sidebar.html

server/routes/index.js, server/routes/user.js
Edit routing GET '/logout' in index.js
Edit routing DELETE '/user' in user.js and try-catch syntax
=> [Edit] Edit index.js, user.js

src/app/index.route.js, src/app/layout/layout.controller.js, src/app/layout/login.controller.js, src/app/layout/login.html, src/app/layout/sidebar/admin.sidebar.html, src/app/layout/sidebar/sidebar.html, src/app/main/main.html
Remove Korean and translate every word to English.
=>  [Edit] Index.route.js and three other files
